---
- name: Setup docker package and socket
  gather_facts: false
  hosts: all

  vars:
    main_manager: "{{ groups['cluster_manager'][0] }}"
    join_token: ""

  tasks:
    - name: Update system
      ansible.builtin.apt:
        update_cache: true
        upgrade: safe

    - name: Ensure docker.io is installed
      ansible.builtin.apt:
        name:
          - docker.io
        state: present

    - name: Ensure docker-compose is installed
      ansible.builtin.apt:
        name:
          - docker-compose
        state: present

    - name: Ensure docker.socket is running
      ansible.builtin.systemd_service:
        name: docker.socket
        enabled: true
        state: started

    - name: Gather networking facts
      ansible.builtin.setup:
        gather_subset:
          - network

    - name: Swarm init
      ansible.builtin.command: "docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}"
      when: inventory_hostname == main_manager
      register: swarm_init
      failed_when: swarm_init.rc != 0
      changed_when: true

    - name: Get manager token
      ansible.builtin.command: "docker swarm join-token -q manager"
      when: inventory_hostname == main_manager
      register: manager_token
      failed_when: manager_token.rc != 0
      changed_when: false

    - name: Get worker token
      ansible.builtin.command: "docker swarm join-token -q worker"
      when: inventory_hostname == main_manager
      register: worker_token
      failed_when: worker_token.rc != 0
      changed_when: false

    - name: Set token
      ansible.builtin.set_fact:
        join_token: >
          "{{ hostvars[groups['cluster_manager'][0]].manager_token.stdout
          if (inventory_hostname in groups['cluster_manager'])
          else hostvars[groups['cluster_manager'][0]].worker_token.stdout }}"
      when: not ansible_check_mode

    - name: Join the Swarm
      ansible.builtin.command: >
        "docker swarm join --token {{ join_token }} {{ main_manager }}:2377
        --advertise-addr {{ ansible_default_ipv4.address }}"
      when: inventory_hostname != main_manager
      register: join_swarm
      failed_when: join_swarm.rc != 0
      changed_when: true
