playbook := "playbook.yaml"

default: check dry

fmt:
    @echo "TODO fmt"

check:
    ansible-playbook {{playbook}} --syntax-check

dry:
    ansible-playbook {{playbook}} --check

deploy:
    ansible-playbook {{playbook}}
